title: Dimitriape
description: Dimitrije Ape Stevanovic Rant Out Crazyness
show_downloads: false
google_analytics:
theme: jekyll-theme-midnight
github:
  owner_name: ljrzarate
  owner_url: https://github.com/ljrzarate
baseurl: /dimitriape
